import { prismaClient } from "./db";
import express from "express";



export const app = express();

app.use(express.json());

app.post("/sum", async (req, res) => {
  const a = req.body.a;
  const b = req.body.b;

  if (a > 1000000 || b > 1000000) {
    res.status(422).json({ message: "Cannot support larger numbers" });
    return;
  }

  const answer = a + b;

  const response = await prismaClient.request.create({
    data: {
      a: a,
      b: b,
      answer: answer,
      type: "ADD",
    },
  });

  console.log(response);

  // we are logging response to see the id generated by prisma mock
  // the values we mocked manually in test file for just some specific
  // case , we will get that value here when we run the test

  res.status(200).json({ answer: answer, id: response.id });
});